#ifndef _KEYPAD_CONFIG_H_ 
#define _KEYPAD_CONFIG_H_ 

//KEYPAD PINS
#define KEYPAD_A_PORTID DPORTC
#define KEYPAD_A_PINID PIN0

#define KEYPAD_B_PORTID DPORTC
#define KEYPAD_B_PINID PIN1

#define KEYPAD_C_PORTID DPORTC
#define KEYPAD_C_PINID PIN2

#define KEYPAD_D_PORTID DPORTC
#define KEYPAD_D_PINID PIN3

#define KEYPAD_1_PORTID DPORTC
#define KEYPAD_1_PINID PIN4

#define KEYPAD_2_PORTID DPORTC
#define KEYPAD_2_PINID PIN5

#define KEYPAD_3_PORTID DPORTC
#define KEYPAD_3_PINID PIN6

#define KEYPAD_4_PORTID DPORTC
#define KEYPAD_4_PINID PIN7

#define KEYPAD_ROW_NUM 4
#define KEYPAD_COLUMN_NUM 4


#endif